### ISSUE TITLE
"raptor-0.99.003-linux.jar" crashes after selecting "English" for the interface.

### ISSUE THREAD

**Issue by Unihedro** [evilwan/raptor-chess-interface#1]
It's a `NullPointerException`, so something is wrong with the code. This happens both during a terminal session and double clicking from the interface. I'm on Ubuntu 14.04.2 LTS.

```
unihedron@awesomecomputer:~/Desktop$ java -jar raptor-0.99.003-linux.jar 
21:50:00,143 ERROR RaptorPreferenceStore:40 - Error reading or writing to file 
java.lang.NullPointerException
    at raptor.pref.RaptorPreferenceStore.applyDefaultTheme(RaptorPreferenceStore.java:456)
    at raptor.pref.RaptorPreferenceStore.loadDefaults(RaptorPreferenceStore.java:817)
    at raptor.pref.RaptorPreferenceStore.<init>(RaptorPreferenceStore.java:185)
    at raptor.Raptor.init(Raptor.java:669)
    at raptor.Raptor.createInstance(Raptor.java:100)
    at raptor.Raptor.main(Raptor.java:139)
21:50:00,151 ERROR Raptor:40 - Error occured in main: (If this is a widget is disposed error just ignore it its nothing)
java.lang.RuntimeException: java.lang.NullPointerException
    at raptor.pref.RaptorPreferenceStore.<init>(RaptorPreferenceStore.java:197)
    at raptor.Raptor.init(Raptor.java:669)
    at raptor.Raptor.createInstance(Raptor.java:100)
    at raptor.Raptor.main(Raptor.java:139)
Caused by: java.lang.NullPointerException
    at raptor.pref.RaptorPreferenceStore.applyDefaultTheme(RaptorPreferenceStore.java:456)
    at raptor.pref.RaptorPreferenceStore.loadDefaults(RaptorPreferenceStore.java:817)
    at raptor.pref.RaptorPreferenceStore.<init>(RaptorPreferenceStore.java:185)
    ... 3 more
21:50:00,215  WARN Raptor:48 - Error shutting down ConnectorService
java.lang.ExceptionInInitializerError
    at raptor.service.ConnectorService.<init>(ConnectorService.java:36)
    at raptor.service.ConnectorService.<clinit>(ConnectorService.java:27)
    at raptor.Raptor.shutdownWithoutExit(Raptor.java:518)
    at raptor.Raptor.shutdown(Raptor.java:661)
    at raptor.Raptor.shutdown(Raptor.java:499)
    at raptor.Raptor.main(Raptor.java:251)
Caused by: java.lang.NullPointerException
    at raptor.chess.util.GameUtils.getChessPieceCharacter(GameUtils.java:243)
    at raptor.connector.fics.FicsConnector.<clinit>(FicsConnector.java:85)
    ... 6 more
Exception in thread "main" java.lang.NullPointerException
    at raptor.Raptor.shutdownWithoutExit(Raptor.java:524)
    at raptor.Raptor.shutdown(Raptor.java:661)
    at raptor.Raptor.shutdown(Raptor.java:499)
    at raptor.Raptor.main(Raptor.java:251)
unihedron@awesomecomputer:~/Desktop$ _
```

**Comment by evilwan** [comment]
Hello,

Thanks for reporting the issue. My first guess would be that you did not run the resources jar before running the program?

The resources (images of pieces, screen backgrounds, sounds...) are stored in a platform independent jar. The idea is that they will not change as frequently as the program itself, so that the downloads stay much smaller.

The drawback is that you will have to download and run the resources jar at least once (before running Raptor itself) The stacktrace that you sent starts with this "...RaptorPreferenceStore.applyDefaultTheme..." which makes me guess that the resources are not in place (cannot find the default theme)

Also note that the resources are stored per user, so each user will have to install them before running Raptor.

Regards.

**Comment by evilwan** [comment]
Ok, tried to reproduce myself and got a similar (but different) error if I first clean out the local ~/.raptor directory tree (so start without any previous Raptor install) The error you mention is shown if I launch Raptor without previous run of the resources jar.

Will look into the problem.

Meanwhile, a workaround might be to first install the old installer on Google Code and then proceed with running the new resources jar, followed by launching the new jar.

**Comment by evilwan** [comment]
Hi,

Quick workaround: after running the resources jar, also execute the following command:

mkdir ~/.raptor/games

Once that directory is created, Raptor should startup.

Code fix to follow later.

**Comment by Unihedro** [comment]
Thanks for the responses! The last command did it. Thanks a lot!

**Comment by evilwan** [comment]
Version 0.99.004 should fix the problem: the manual command should no longer be necessary.
