### ISSUE TITLE
Raptor Error when managing tabs in GUI.

### ISSUE THREAD

**Issue by Unihedro** [evilwan/raptor-chess-interface#5]
This is the error log that comes in a popup:

```
Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error in execute
IllegalArgumentException: Argument not valid
java.lang.IllegalArgumentException: Argument not valid
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.SWT.error(Unknown Source)
    at org.eclipse.swt.custom.CTabFolder.removeTabControl(Unknown Source)
    at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
    at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
    at raptor.RaptorWindow$RaptorTabFolder.updateToolbar(RaptorWindow.java:326)
    at raptor.RaptorWindow.restoreFolders(RaptorWindow.java:2623)
    at raptor.RaptorWindow$51$1.execute(RaptorWindow.java:2249)
    at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
    at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at raptor.Raptor.main(Raptor.java:235)
```

**Comment by evilwan** [comment]
Hi,

Could you please provide more details about the platform you are using
(windows, linux, mac...) and what you were trying to do in the application?
(meaning: how to get to the point of error)

Thanks.

On Wed, Jul 1, 2015 at 11:47 AM, Unihedron notifications@github.com wrote:

> This is the error log that comes in a popup:
> 
> Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
>   Help -> Report Issue
> 
> Error in execute
> IllegalArgumentException: Argument not valid
> java.lang.IllegalArgumentException: Argument not valid
>     at org.eclipse.swt.SWT.error(Unknown Source)
>     at org.eclipse.swt.SWT.error(Unknown Source)
>     at org.eclipse.swt.SWT.error(Unknown Source)
>     at org.eclipse.swt.custom.CTabFolder.removeTabControl(Unknown Source)
>     at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
>     at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
>     at raptor.RaptorWindow$RaptorTabFolder.updateToolbar(RaptorWindow.java:326)
>     at raptor.RaptorWindow.restoreFolders(RaptorWindow.java:2623)
>     at raptor.RaptorWindow$51$1.execute(RaptorWindow.java:2249)
>     at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
>     at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
>     at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
>     at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
>     at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
>     at org.eclipse.jface.window.Window.open(Window.java:801)
>     at raptor.Raptor.main(Raptor.java:235)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/evilwan/raptor-chess-interface/issues/5.

## 

---

I think I've got the hang of it now... :w :q :wq :wq! ^d X exit X Q

:quitbye

CtrlAltDel ~~q :~q logout save/quit :!QUIT ^[zz ^[ZZ ZZZZ ^H ^@ ^L ^[c
^# ^E
^X ^I ^T ? help helpquit ^D ^d ^C ^c helpexit ?Quit ?q ^Kx /QY sync

##  halt
